#!/usr/bin/env ruby

class Provision
  class << self

    def call
      ensure_secret
      ensure_deployment
      ensure_service
      puts "EventSource provisioned successfully"
    end

    def ensure_secret
      return if Kernel.system(*%W[kubectl get secret/pubsub -o name], err: :out, out: "/dev/null")

      abort "PubSub secrets are not configured. Make sure you have them provisioned from the infrastructure repository."
    end

    def ensure_deployment
      kube_apply "deployment"
    end

    def ensure_service
      kube_apply "service"
    end

    def kube_apply(filename)
      file = File.join(File.expand_path("..", __FILE__), "#{filename}.yaml")
      Kernel.system(*%W[kubectl apply -f #{file}], out: "/dev/null")
    end
  end
end

Provision.call
