#!/usr/bin/env ruby

require "erb"
require "open3"

class Provision
  class << self

    def call
      help if ARGV[0] == "-h" || ARGV[0] == "--help"

      ensure_secret
      ensure_deployment
      ensure_service
      puts "EventSource provisioned successfully for environment '#{environment}'"
    end

    def help
      puts "Usage: provision [environment] [topic_name]"
      puts
      puts "Environment defaults to 'staging'"
      exit 1
    end

    def ensure_secret
      return if Kernel.system(*%W[kubectl get secret/pubsub -o name], err: :out, out: "/dev/null")

      abort "PubSub secrets are not configured. Make sure you have them provisioned from the infrastructure repository."
    end

    def ensure_deployment
      apply_file "deployment"
    end

    def ensure_service
      apply_file "service"
    end

    def apply_file(filename)
      file = File.join(File.expand_path("..", __FILE__), "#{filename}.yaml.erb")
      resource = ERB.new(File.read(file)).result(binding)
      kube_apply(resource) || abort("Error applying file #{filename}")
    end

    def kube_apply(resource)
      Open3.popen2e("kubectl apply --record=true -f -") do |stdin, out_err, wait_thr|
        stdin.write resource
        stdin.close
        output = out_err.read
        if wait_thr.value.success?
          true
        else
          puts output
          false
        end
      end
    end

    def environment
      ARGV[0] || "staging"
    end

    def topic_name
      return ARGV[1] if ARGV[1]

      case environment
      when "staging"
        "eventsource-staging"
      when "production"
        "eventsource"
      else
        abort("Don't know what topic name to use for this environment. Please provide one. See --help for more information")
      end
    end
  end
end

Provision.call
