apiVersion: v1
kind: Service
metadata:
  name: eventsource
spec:
  type: NodePort
  selector:
    component: eventsource
  ports:
    - name: sse
      port: 80
      targetPort: 80
      nodePort: 32765
      protocol: TCP
  sessionAffinity: None
