apiVersion: v1
kind: Service
metadata:
  name: eventsource
spec:
  type: ClusterIP
  selector:
    component: eventsource
  ports:
    - name: sse
      port: 80
      protocol: TCP
      targetPort: 80
  sessionAffinity: None
