{{- if eq .Values.provider "gke" }}
apiVersion: cloud.google.com/v1beta1
kind: BackendConfig
metadata:
  name: {{ include "go-eventsource.fullname" . }}
spec:
  timeoutSec: {{ .Values.backendConfig.timeout }}
{{- end -}}