apiVersion: apps/v1
kind: Deployment
metadata:
  name: eventsource
  labels:
    component: eventsource
    environment: {{ .Values.environment }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      component: eventsource
      environment: {{ .Values.environment }}
  template:
    metadata:
      labels:
        component: eventsource
        environment: {{ .Values.environment }}
    spec:
{{ include "go-eventsource.affinity" . | indent 6 }}
      containers:
      - name: eventsource
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        image: {{ include "go-eventsource.image" . | quote }}
        ports:
        - name: sse
          containerPort: 80
        resources:
          requests:
            cpu: {{ .Values.resources.requests.cpu | quote }}
            memory: {{ .Values.resources.requests.memory | quote }}
          limits:
            cpu: {{ .Values.resources.limits.cpu | quote }}
            memory: {{ .Values.resources.limits.memory | quote }}
        env:
{{- range $pair := .Values.environment_variables }}
        - name: {{ $pair.name }}
          value: {{ tpl $pair.value $ | quote }}
{{- end }}
        - name: ES_SUBSCRIPTION
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
{{- if eq .Values.provider "gke" }}
        - name: PUBSUB_PROJECT_ID
          valueFrom:
            secretKeyRef:
              name: pubsub
              key: project-id
        volumeMounts:
          - name: pubsub-secret
            readOnly: true
            mountPath: /etc/pubsub
      volumes:
        - name: pubsub-secret
          secret:
            secretName: pubsub
{{- end }}
