{{- if .Values.pdb.enabled }}
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: eventsource
spec:
  selector:
    matchLabels:
      component: eventsource
  minAvailable: 50%
{{- end -}}
