{{- if .Values.pdb.enabled }}
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name:  {{ include "go-eventsource.fullname" . }}
spec:
  selector:
    matchLabels:
      component:  {{ include "go-eventsource.fullname" . }}
  minAvailable: 50%
{{- end -}}
