apiVersion: v1
kind: Service
metadata:
  name: eventsource
  labels:
    environment: {{ .Values.environment }}
spec:
  type: {{ .Values.service.type }}
  selector:
    component: eventsource
    environment: {{ .Values.environment }}
  ports:
    - name: sse
      port: {{ .Values.service.type }}
      targetPort: {{ .Values.service.type }}
      protocol: TCP
  sessionAffinity: None
