apiVersion: v1
kind: Service
metadata:
  name:  {{ include "go-eventsource.fullname" . }}
  labels:
    environment: {{ .Values.environment }}
{{- if eq .Values.provider "gke" }}
  annotations:
    beta.cloud.google.com/backend-config: '{"ports": {"{{ .Values.service.port }}":"eventsource"}}'
{{- end }}
spec:
  type: {{ .Values.service.type }}
  selector:
    component:  {{ include "go-eventsource.fullname" . }}
    environment: {{ .Values.environment }}
  ports:
    - name: sse
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
  sessionAffinity: None
